services:
  postgres:
    image: postgres:14.6
    container_name: todolist_dev_postgres
    networks:
      - todolist_dev
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=America/Belem
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=Fo0#97oXggSQ
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    restart: on-failure

  todolist:
    build:
      context: "."
      target: development
      dockerfile: "deploy/docker/Dockerfile.dev"
    container_name: todolist_todolist_dev
    working_dir: /workspaces/app
    networks:
      - todolist_dev
    volumes:
      - ./.docker/go/bin:/go/bin:rw
      - ./.docker/go/pkg:/go/pkg:rw
      - ./:/go/src/todolist:rw
    environment:
      - TZ=America/Belem
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: on-failure
    tty: true

networks:
  todolist_dev:
    driver: bridge
